baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Jekyll'

collections:
  sftcomponents:
    output: true
    permalink: /component/:path/

defaults:
  - scope:
      type: sftcomponents
    values:
      layout: sftcomponent
      bodyClass: page-sftcomponent-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
